### ISSUE TITLE
Uncaught TypeError: (0 , _steps.Before) is not a function

### ISSUE THREAD

**Issue by pravynandas** [TheBrainFamily/cypress-cucumber-example#12]
Cypress: 3.8.1
cypress-cucumber-preprocessor: 1.11.0

Google.Feature's Before() produces this error.

`
import { Given, Then, Before } from "cypress-cucumber-preprocessor/steps";

const url = "https://google.com";

let myBeforeCount = 0;

// This verifies that the hooks work with bundling feature
// https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/234
Before(() => {
  expect(myBeforeCount).to.be.lessThan(2);
  myBeforeCount += 1;
});

`

Solution: Is to update cypress-cucumber-preprocessor to version 1.16.2 in package.json.

**Comment by lgandecki** [comment]
Thanks, do you want to create a small PR?

**Comment by pravynandas** [comment]
Yup. On it as we speak.

**Comment by pravynandas** [comment]
My First Pull-Request [PR#13](https://github.com/TheBrainFamily/cypress-cucumber-example/pull/13) posted. Please correct me if any errors.

**Comment by lgandecki** [comment]
thank you!

**Comment by pravynandas** [comment]
Thanks for the awesome tool.
