### ISSUE TITLE
Can not work well on windows 10

### ISSUE THREAD

**Issue by Pearl4C** [TheBrainFamily/cypress-cucumber-example#14]
Error: Cannot find module 'E:democypress-cucumber-example
ode_modulescypress-cucumber-preprocessorlib/createTestsFromFeature' from 'E:\demo\cypress-cucumber-example\cypress\integration\common'

**Comment by pravynandas** [comment]
Appears to be an issue in the way path has been given. Can you provide some more inputs or perhaps a sample of file/module under /common folder?

I do not seem to have any issues running this repo on my windows 10.

**Comment by Pearl4C** [comment]
> Appears to be an issue in the way path has been given. Can you provide some more inputs or perhaps a sample of file/module under /common folder?
> 
> I do not seem to have any issues running this repo on my windows 10.

I just download the source code，do "npm install" & "npm run test", then ...
Error: Cannot find module 'E:democypresscypress-cucumber-example
ode_modulescypress-cucumber-preprocessorlib/resolveStepDefinition' from 'E:\demo\cypress\cypress-cucumber-example\cypress\integration\socialNetworks'

**Comment by pravynandas** [comment]
I see an issue in the path you supplied. I think github is suppressing the forwardslash (\/) and backslashes (\\) making it hard to understand what is the actual path in error. Also seems the 'n' in node_module is treated as new line and **ode_modules** moved to next line. You can use backslash (\\) to escape special characters and use 'Preview' before hitting comment to be sure. 

Coming to the issue, nothing appears to be abnormal. including the "npm run test" command which simply runs the default *.feature files supplied in this repo.

**Comment by Pearl4C** [comment]
> I see an issue in the path you supplied. I think github is suppressing the forwardslash (/) and backslashes (\) making it hard to understand what is the actual path in error. Also seems the 'n' in node_module is treated as new line and **ode_modules** moved to next line. You can use backslash (\) to escape special characters and use 'Preview' before hitting comment to be sure.
> 
> Coming to the issue, nothing appears to be abnormal. including the "npm run test" command which simply runs the default *.feature files supplied in this repo.

Modified **'cypress/integration/common/I_see_STRING_in_the_title.js' 'cypress/integration/news/Google/different.js' 'cypress/integration/news/Google/openingGoogle.js' 'cypress/integration/socialNetworks/Facebook/different.js'  'cypress/integration/socialNetworks/Facebook/openingFacebook.js' 'cypress/integration/socialNetworks/Twitter/openingTwitter.js'**
cypress-cucumber-preprocessor/steps -->E:/demo/cypress/cypress-cucumber-example\/node_modules/cypress-cucumber-preprocessor/steps

then:
The error was:
Error: Cannot find module 'E:democypresscypress-cucumber-example
ode_modulescypress-cucumber-preprocessorlib/createTestsFromFeature' from 'E:\demo\cypress\cypress-cucumber-example\cypress\integration\news'

**Comment by antonio-zenoo** [comment]
Just modifying packaje json like this does the trick
```
  "dependencies": {
    "cypress": "^3.4.1",
    "cypress-cucumber-preprocessor": "1.18.0"
  },
```

The issue with Windows 10 started with a modification that went into 1.19.0

**Comment by Pearl4C** [comment]
> Just modifying packaje json like this does the trick
> 
> ```
>   "dependencies": {
>     "cypress": "^3.4.1",
>     "cypress-cucumber-preprocessor": "1.18.0"
>   },
> ```
> 
> The issue with Windows 10 started with a modification that went into 1.19.0
antonio-zenoo ，
Thanks very much, you solved my problem!

**Comment by antonio-zenoo** [comment]
FYI with version 2.0.1 this has been fixed.
