### ISSUE TITLE
unable to skip test scenarios with Cypress/Cucumber implementation

### ISSUE THREAD

**Issue by leevkron** [TheBrainFamily/cypress-cucumber-example#21]
I'm new to this so bear with me.

I'm unable to skip test scenarios from feature files with an @skip tag. The console output is `TypeError: this.skip is not a function` 

OS: Mac OS Catalina (UTD)
Test Framework: Cypress with Cucumber Preprocessor
Browser: Chrome
cucumber: "6.0.5",
cypress: "4.7.0",
cypress-commands: "^1.1.0",
cypress-cucumber-preprocessor: "^2.4.0",
mocha": "^7.2.0"

Please let me know of any more information you would like.

**Comment by jprealini** [comment]
paste your cypress.json content here, and your feature file content

**Comment by leevkron** [comment]
I have since gone another direction with my testing set up. Feel free to close this if you like. I have removed Cucumber from my testing requirements.

**Comment by leevkron** [comment]
Closed
