### ISSUE TITLE
Request: Add Scenario outline implementation

### ISSUE THREAD

**Issue by tmarhem** [TheBrainFamily/cypress-cucumber-example#28]
Hello,

From what I have seen in the repo Scenario Outlines are now handled by cypress-cucumber.
Althought I am struggling finding the syntax for the variables in the case of a Scenario Outline inplemented in Cypress.
Anyone could add a working example to the repository ?

Thank you :)

**Comment by lgandecki** [comment]
Hello

take a look at this .feature file:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/ScenarioOutline.feature

and matching step defs
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/scenario_outline_data_table.js

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/scenario_outline_integer.js

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/scenario_outline_multiple_vars.js

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/scenario_outline_string.js
