### ISSUE TITLE
Scoped hooks aren't working in demo app

### ISSUE THREAD

**Issue by dchasepdx** [TheBrainFamily/cypress-cucumber-example#5]
It appears scoped hooks aren't working in the demo app. When you run all tests, the before hook that states it only runs during the Google tests is run during all tests. 

Google test suite
<img width="897" alt="googlenews" src="https://user-images.githubusercontent.com/19154684/52427990-ea4ef100-2ab5-11e9-9d40-519413adecc2.png">

Facebook test suite
<img width="891" alt="facebook" src="https://user-images.githubusercontent.com/19154684/52428065-0fdbfa80-2ab6-11e9-9081-4fb86b3c69e8.png">

repro steps: clone the demo app, run cypress, and run all tests.

I was having issues with scoped step definitions in a project and I wanted to make sure it wasn't a weird configuration on my end. I'm wondering if this is a bug with scoped step definitions and if I should file an issue against the main repo. 

Thanks

**Comment by lgandecki** [comment]
Hello, 

this is the problem described here:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/139
which is an acknowledged bug in cypress itself:

https://github.com/cypress-io/cypress/issues/3323

I will add an info here to NOT use "run all" in the GUI - I don't think this is something worth doing anyway - once you have a realistic number of features, you wouldn't be running them all through GUI anyway (and it works properly when you do cypress run)

**Comment by dchasepdx** [comment]
Thanks so much for the quick reply @lgandecki. I'm glad to hear it was just a problem with how I was running tests. I'll go ahead and close the issue.
